function cellInfo = object(varargin) 
% OBJECT returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'in', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'sin', 1, 'single', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'cos', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'count', 1, 'uint8', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'out', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'floor_sin', 1, 'int8', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ceiling_cos', 1, 'int8', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'half_count', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'to_mcap', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'in', 1, 'in', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'out', 1, 'out', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
